version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
