trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '-c "$(BuildConfiguration)" -p:Platform:"$(BuildPlatform)"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/**/*.Test.csproj'
    arguments: '-c "$(BuildConfiguration)" --no-build -v normal'
