trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '-c $(Configuration) -v normal'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'src/**/*.Test.csproj'
    arguments: '-c $(Configuration) --no-build --collect:\"Code Coverage\" -s CodeCoverage.runsettings -v normal'
