trigger:
- master

pr:
- master

# Windows is used for the project because it supports code coverage out-of-the-box
pool:
  vmImage: 'windows-latest'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/Sweetener*/Sweetener*.csproj'
    arguments: '-c $(Configuration) -v normal'

# "-s|--settings" option uses the project directory as the working directory, such that
# the below task only works for project files 2 directories down from the root of the repository.
# Note that "Debug" code coverage may insert "code blocks" that are only partially covered
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'src/Sweetener*.Test/Sweetener*.Test.csproj'
    arguments: '-c $(Configuration) --no-build --collect "Code Coverage" -s ../../CodeCoverage.runsettings -v normal'
