parameters:
- name: project
  type: string
  default: ''
- name: type
  type: string
  default: ''

jobs:
- job: Validate
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Debug'
  steps:
  - template: ../../Templates/Steps.Validate.yml
    parameters:
      project: '${{ parameters.Project }}'
      type: '${{ parameters.Type }}'
      buildConfiguration: '$(BuildConfiguration)'

- job: Package
  dependsOn: Validate
  condition: succeeded()
  pool:
    vmImage: 'windows-latest'
  variables:
    buildConfiguration: 'Release'
    netfxTools: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools'
  steps:
  - template: Steps.Package.yml
    parameters:
      project: '${{ parameters.Project }}'
      type: '${{ parameters.Type }}'
      buildConfiguration: '$(BuildConfiguration)'
      netfxTools: '$(NetFXTools)'
