# Note: Only certain pipelines have access to the necessary resources for signing
parameters:
- name: project
  type: string
  default: ''

jobs:
- job: Validate
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Debug'
  steps:
  - template: ../Steps.Validate.yml
    parameters:
      project: '${{ parameters.Project }}'
      buildConfiguration: '$(BuildConfiguration)'

- job: Build
  dependsOn: Validate
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
  steps:
  - template: Steps.Build.yml
    parameters:
      project: '${{ parameters.Project }}'
      buildConfiguration: '$(BuildConfiguration)'
