pr:
  branches:
    include:
    - master
  paths:
    include:
    - eng/PR/Sweetener.Reliability.yml
    - eng/PR/Templates/*
    - eng/Scripts/*
    - eng/Templates/*
    - src/AssemblyInfo.Common.cs
    - src/Directory.Build.props
    - src/Sweetener.sln
    - src/Sweetener.Reliability/*
trigger: none

jobs:
- template: Templates/Jobs.yml
  parameters:
    project: 'Sweetener.Reliability'
