name: github release
description: Creates a GitHub release for a NuGet package
inputs:
  project:
    description: The name of the component
    required: true
  packageDirectory:
    description: The directory containing the NuGet package
    required: true
  token:
    description: The GitHub PAT token
    required: true

runs:
  using: composite
  steps:
    - name: Parse Version
      id: package
      shell: pwsh
      run: |
        ./.github/actions/github-release/scripts/ParseVersion.ps1 `
          -ProjectName '${{ inputs.project }}' `
          -PackageDirectory '${{ inputs.packageDirectory }}'

    - name: Check Exists
      id: release
      shell: pwsh
      continue-on-error: true
      run: |
        gh release view '${{ steps.package.outputs.tag }}' | Out-Null
        Write-Host "::set-output name=exists::$($?)"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Tag
      if: ${{ steps.release.outputs.exists == 'false' }}
      shell: bash
      run: |
        git tag -s -m "${{ inputs.project }} Version ${{ steps.package.outputs.version }}" \
          ${{ steps.package.outputs.tag }} \
          ${{ github.sha }}
        git push origin ${{ steps.package.outputs.tag }}

    - name: Create Release
      if: ${{ steps.release.outputs.exists == 'false' }}
      working-directory: ${{ inputs.packageDirectory }}
      shell: bash
      run: |
        gh release create ${{ steps.package.outputs.tag }} ${{ steps.package.outputs.name }} ${{ steps.package.outputs.prerelease }} \
          --title "${{ inputs.project }} ${{ steps.package.outputs.version }}" \
          --draft
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
