pr: none
trigger: none
resources:
  pipelines:
  - pipeline: Sweetener
    source: 'CI/Sweetener - CI'
    trigger:
      branches:
        include:
        - main

jobs:
- template: ../Templates/Jobs.yml
  parameters:
    project: 'Sweetener'
    type: 'Core'
    sourcePipelineId: 8
