name: dotnet pack
description: Packages a .NET project and uploads the result as an artifact
inputs:
  project:
    description: The name of the csproj file
    required: true
  solution:
    description: The name of the solution file
    required: true
  buildConfiguration:
    default: Debug
    description: The dotnet build configuration
    required: false

runs:
  using: composite
  steps:
    - name: Setup
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '5.0.x'

    - name: Determine Version
      id: version
      shell: pwsh
      run: |
        ./eng/Scripts/ParseVersion.ps1 `
          -VersionFilePath './src/${{ inputs.solution }}/${{ inputs.project }}/Version.json' `
          -BuildId '${{ github.run_attempt }}'

    - name: Build
      shell: bash
      run: |
        dotnet pack "./src/${{ inputs.solution }}/${{ inputs.project }}/${{ inputs.project }}.csproj" \
          -c "${{ inputs.buildConfiguration }}" \
          "-p:ContinuousIntegrationBuild=true;AssemblyVersion=${{ steps.version.outputs.assembly }};FileVersion=${{ steps.version.outputs.file }};InformationalVersion=${{ steps.version.outputs.file }};PackageVersion=${{ steps.version.outputs.package }}" \
          -warnaserror \
          -o "${{ runner.temp }}/package"

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Package
        path: ${{ runner.temp }}/package
