parameters:
  project: ''
  netfxTools: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools'

jobs:
- job: Build

  pool:
    vmImage: 'windows-latest'

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: |
        src/${{ parameters.Project }}/${{ parameters.Project }}.csproj
        src/${{ parameters.Project }}.Test/${{ parameters.Project }}.Test.csproj
      arguments: '-c $(BuildConfiguration) -p:ContinuousIntegrationBuild=true'

  - task: DownloadSecureFile@1
    name: SigningKey
    displayName: 'Download Signing Key'
    inputs:
      secureFile: 'Sweetener.snk'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: PowerShell@2
    displayName: 'Enhanced Strong Name Signing'
    inputs:
      targetType: 'inline'
      script: |
        $assemblies = @(Get-ChildItem -Path "src/${{ parameters.Project }}/bin/$(BuildConfiguration)/" -Recurse -Include ${{ parameters.Project }}.dll)
        foreach ($assembly in $assemblies)
        {
            Start-Process -FilePath "${{ parameters.netfxTools }}/sn.exe" -ArgumentList "-Ra","$assembly","$(SigningKey.SecureFilePath)" -NoNewWindow -Wait
        }
      pwsh: true
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # Note that "Debug" code coverage may result in inaccurate code coverage metrics
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: 'src/${{ parameters.Project }}.Test/${{ parameters.Project }}.Test.csproj'
      arguments: '-c $(BuildConfiguration) --no-build --collect "Code Coverage" -s "$(Build.Repository.LocalPath)/src/CodeCoverage.runsettings" -v normal'

  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      projects: 'src/${{ parameters.Project }}/${{ parameters.Project }}.csproj'
      nobuild: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      artifactName: 'pkg'
