# Note: Only certain pipelines have access to the necessary resources for signing
parameters:
- name: project
  type: string
  default: ''

jobs:
- job: Validate
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Debug'
  steps:
  - template: ../Steps.Validate.yml
    parameters:
      project: '${{ parameters.Project }}'
      buildConfiguration: '$(BuildConfiguration)'

- job: Build
  dependsOn: Validate
  condition: succeeded()
  pool:
    vmImage: 'windows-latest'
  variables:
    buildConfiguration: 'Release'
    netfxTools: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools'
  steps:
  - template: Steps.Build.yml
    parameters:
      project: '${{ parameters.Project }}'
      buildConfiguration: '$(BuildConfiguration)'
      netfxTools: '$(NetFXTools)'
