pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - eng/CI/Sweetener.yml
    - eng/CI/Scripts/*
    - eng/CI/Templates/*
    - eng/Scripts/*
    - eng/Templates/*
    - src/AssemblyInfo.Common.cs
    - src/Directory.Build.props
    - src/Sweetener.sln
    - src/Sweetener/*

jobs:
- template: Templates/Jobs.yml
  parameters:
    project: 'Sweetener'
