name: Check Code Coverage
description: Validates code coverage and uploads the results.
inputs:
  reportPath:
    description: The path to the cobertura coverage file.
    required: true
  flag:
    description: The Codecov flag that identifies the specific coverage within the mono repo
    required: true
runs:
  using: composite
  steps:
    - name: Copy Code Coverage
      shell: pwsh
      run: |
        New-Item -ItemType 'directory' -Path '${{ runner.temp }}/codecoverage/' | Out-Null
        Copy-Item '${{ inputs.reportPath }}' -Destination '${{ runner.temp }}/codecoverage/'

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Coverage
        path: ${{ runner.temp }}/codecoverage

    - name: Codecov Upload
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ${{ runner.temp }}/codecoverage/coverage.cobertura.xml
        flags: ${{ inputs.flag }}
        fail_ci_if_error: true
