pr: none
trigger: none
resources:
  pipelines:
  - pipeline: Sweetener_Extensions_Configuration_Abstractions
    source: 'CI/Sweetener.Extensions.Configuration.Abstractions - CI'
    trigger:
      branches:
        include:
        - main

jobs:
- template: Templates/Jobs.yml
  parameters:
    project: 'Sweetener.Extensions.Configuration.Abstractions'
    type: 'Extensions'
    sourcePipelineId: 13
