name: Sweetener.Extensions.Configuration.Binder Pull Request

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/*
    - .github/workflows/sweetener.extensions.configuration.binder-pr.yml
    - src/*
    - src/Extensions/*
    - src/Extensions/Sweetener.Extensions.Configuration.Binder/*
    - src/Shared/*

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-validate
        with:
          project: Sweetener.Extensions.Configuration.Binder
          solution: Extensions
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Ensure Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        uses: ./.github/actions/dotnet-package
        with:
          project: Sweetener.Extensions.Configuration.Binder
          solution: Extensions
          buildConfiguration: Release
          buildId: ${{ github.run_attempt }}
