name: Sweetener Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
    - .github/actions/*
    - .github/workflows/sweetener-ci.yml
    - src/*
    - src/Core/*
    - src/Core/Sweetener/*
    - src/Shared/*

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Ensure Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml

  package:
    name: Package
    runs-on: windows-latest
    if: ${{ success() }}

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch Key Vault Secrets
        uses: Azure/get-keyvault-secrets@v1
        id: keyvault
        with:
          keyvault: Sugarman-KeyVault
          secrets: 'Sweetener-Strong-Name-Key'

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener
          solution: Core
          buildConfiguration: Release
          sign: true
          strongNameKey: ${{ steps.keyvault.outputs.Sweetener-Strong-Name-Key }}
          accessToken: ${{ env.ACTIONS_RUNTIME_TOKEN }}

      - name: Azure Logout
        shell: bash
        if: ${{ always() }}
        run: |
          az logout
          az cache purge
          az account clear

  push:
    name: Push
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Package
        uses: ./.github/actions/dotnet-push
        with:
          apiKey: ${{ secrets.NUGET_API_KEY }}
