name: Sweetener.Extensions.Configuration.Abstractions PR

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/**
    - .github/workflows/sweetener.extensions.configuration.abstractions-pr.yml
    - global.json
    - NuGet.config
    - src/*
    - src/Extensions/*
    - src/Extensions/Sweetener.Extensions.Configuration.Abstractions/**
    - src/Shared/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener.Extensions.Configuration.Abstractions
          solution: Extensions
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml
          flag: ext.config.abstractions

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener.Extensions.Configuration.Abstractions
          solution: Extensions
          buildConfiguration: Release
          pullRequestNumber: ${{ github.event.pull_request.number }}
