name: Sweetener Pull Request

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/*
    - .github/workflows/sweetener-pr.yml
    - .github/workflows/dotnet-build-test.yml
    - src/*
    - src/Core/*
    - src/Core/Sweetener/*
    - src/Shared/*

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: dotnet test
        uses: ./.github/actions/dotnet-validate
        with:
          project: Sweetener
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults/Sweetener

      - name: Check Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/Sweetener/*/coverage.cobertura.xml

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: dotnet package
        uses: ./.github/actions/dotnet-package
        with:
          project: Sweetener
          solution: Core
          buildConfiguration: Release
