name: Sweetener PR

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/**
    - .github/workflows/sweetener-pr.yml
    - global.json
    - NuGet.config
    - src/*
    - src/Core/*
    - src/Core/Sweetener/**
    - src/Shared/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml
          flag: Sweetener

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener
          solution: Core
          buildConfiguration: Release
          pullRequestNumber: ${{ github.event.pull_request.number }}
