name: Sweetener.Linq PR

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/**
    - .github/workflows/sweetener.linq-pr.yml
    - global.json
    - NuGet.config
    - src/*
    - src/Common/**
    - src/Core/*
    - src/Core/Sweetener.Linq/**
    - src/Core/Sweetener.Linq.Test/**
    - src/Tools/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener.Linq
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults/

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          directory: ${{ runner.temp }}/TestResults/
          flags: Sweetener.Linq
          fail_ci_if_error: true

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener.Linq
          solution: Core
          buildConfiguration: Release
          pullRequestNumber: ${{ github.event.pull_request.number }}
