name: Sweetener.Extensions.Options.ConfigurationExtensions Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
    - .github/actions/**
    - .github/workflows/sweetener.extensions.options.configurationextensions-ci.yml
    - src/*
    - src/Extensions/*
    - src/Extensions/Sweetener.Extensions.Options.ConfigurationExtensions/**
    - src/Shared/**

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener.Extensions.Options.ConfigurationExtensions
          solution: Extensions
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Ensure Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml

  package:
    name: Package
    runs-on: windows-latest
    if: ${{ success() }}

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Az Access Token
        id: auth
        shell: pwsh
        run: |
          $token = $(az account get-access-token | ConvertFrom-Json).accessToken
          Write-Host "::add-mask::$token"
          Write-Host "::set-output name=token::$token"

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener.Extensions.Options.ConfigurationExtensions
          solution: Extensions
          buildConfiguration: Release
          sign: true
          strongNameKey: ${{ secrets.STRONG_NAME_KEY }}
          accessToken: ${{ steps.auth.outputs.token }}

      - name: Azure Logout
        shell: bash
        if: ${{ always() }}
        run: |
          az logout
          az cache purge
          az account clear

  push:
    name: Push
    needs: package
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Package
        uses: ./.github/actions/dotnet-push
        with:
          apiKey: ${{ secrets.NUGET_API_KEY }}
