name: Sweetener PR

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/**
    - .github/workflows/sweetener-pr.yml
    - global.json
    - NuGet.config
    - src/*
    - src/Core/*
    - src/Core/Sweetener/**
    - src/Core/Sweetener.Test/**
    - src/Shared/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          project: Sweetener
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults/

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          directory: ${{ runner.temp }}/TestResults/
          flags: Sweetener
          fail_ci_if_error: true

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package
        uses: ./.github/actions/dotnet-pack
        with:
          project: Sweetener
          solution: Core
          buildConfiguration: Release
          pullRequestNumber: ${{ github.event.pull_request.number }}

  push-test:
    name: Push (Test)
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Package
        uses: actions/download-artifact@v3
        with:
          name: Package
          path: ${{ runner.temp }}/downloads/package

      - name: Create Release
        uses: ./.github/actions/github-release
        with:
          project: Sweetener
          packageDirectory: ${{ runner.temp }}/downloads/package
          token: ${{ secrets.GITHUB_TOKEN }}
