name: Sweetener Continuous Integration

on:
  push:
    branches: [ $default-branch ]
    paths:
    - .github/actions/*
    - .github/workflows/sweetener-pr.yml
    - src/*
    - src/Core/*
    - src/Core/Sweetener/*
    - src/Shared/*

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-validate
        with:
          project: Sweetener
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults/Sweetener

      - name: Ensure Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/Sweetener/*/coverage.cobertura.xml

  package:
    name: Package
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        uses: ./.github/actions/dotnet-package
        with:
          project: Sweetener
          solution: Core
          buildConfiguration: Release
          sign: true
