name: Sweetener Pull Request

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/actions/*
    - .github/workflows/sweetener-pr.yml
    - src/*
    - src/Core/*
    - src/Core/Sweetener/*
    - src/Shared/*

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-validate
        with:
          project: Sweetener
          solution: Core
          resultsDirectory: ${{ runner.temp }}/TestResults/Sweetener

      - name: Ensure Code Coverage
        uses: ./.github/actions/check-code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/Sweetener/*/coverage.cobertura.xml

  package:
    name: Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # Temporarily sign for testing
      - name: Package
        uses: ./.github/actions/dotnet-package
        with:
          project: Sweetener
          solution: Core
          buildConfiguration: Release
          buildId: ${{ github.run_attempt }}
          sign: true
          azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
